<!DOCTYPE html>
<html lang="es-ES">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Actives Manager</title>
  <link rel="shortcut icon" type="image/x-icon" href="<?php echo Conectar::ruta(); ?>images/favicon.ico" />
  <link rel="stylesheet" href="<?php echo Conectar::ruta(); ?>css/style.css" type="text/css" media="all" />
  <link rel="stylesheet" href="<?php echo Conectar::ruta(); ?>css/estilos.css" type="text/css" />
  <link rel="stylesheet" href="<?php echo Conectar::ruta(); ?>css/datePicker.css" type="text/css" />
  <script src="<?php echo Conectar::ruta(); ?>js/jquery-1.8.0.min.js" type="text/javascript"></script>
  <script src="<?php echo Conectar::ruta(); ?>js/date.js" type="text/javascript"></script>
  <script src="<?php echo Conectar::ruta(); ?>js/jquery.datePicker.js" type="text/javascript"></script>
  <!--[if lt IE 9]>
    <script src="js/modernizr.custom.js"></script>
  <![endif]-->
  <script src="<?php echo Conectar::ruta(); ?>js/funciones.js" type="text/javascript"></script>

  <script type="text/javascript">
    function soloNumeros(e, valor){
        key = e.keyCode || e.which;
        tecla = String.fromCharCode(key).toLowerCase();
        letras = "0123456789";
        especiales = [8,9,46,37,39];
        tecla_especial = false
        for(var i in especiales){
            if(key == especiales[i]){
                tecla_especial = true;
                break;
            }
        }
        if(letras.indexOf(tecla)==-1 && !tecla_especial)
            return false;
        //validar solo un punto
        var key = window.event ? e.keyCode : e.which;
        var keychar = String.fromCharCode(key);
        if (valor.indexOf(".")!=-1 && keychar=="."){
            return false;
        }else{
            return true;
            }
    }
    function soloNumerosCantidad(e, valor){
        key = e.keyCode || e.which;
        tecla = String.fromCharCode(key).toLowerCase();
        letras = "0123456789";
        especiales = [8,9,46,37,39];
        tecla_especial = false
        for(var i in especiales){
            if(key == especiales[i]){
                tecla_especial = true;
                break;
            }
        }
        if(letras.indexOf(tecla)==-1 && !tecla_especial)
            return false;
        //Permite no ingresar punto
        var key = window.event ? e.keyCode : e.which;
        var keychar = String.fromCharCode(key);
        if (valor.indexOf(".")!=1 && keychar=="."){
            return false;
        }else{
            return true;
        }
    }
    jQuery(document).ready(function($) {
        $(function()
        {
            $('.fecha_ingreso').datePicker({startDate:'01/01/1996'}).val(new Date().asString());
        });
    });
  </script>
</head>
<body>
<!-- wrapper -->
<div id="wrapper">
  <!-- shell -->
  <div class="shell">
    <!-- container -->
    <div class="container">
      <!-- header -->
      <header id="header">
        <h1 id="logo"><a href="<?php echo Conectar::ruta();?>">Active</a></h1>
      </header>
      <!-- end of header -->
      <!-- navigaation -->
      <nav id="navigation">
        <?php
        if (isset($_SESSION["ses_id"]) and isset($_SESSION["privilegio"]) and $_SESSION["privilegio"]=='administrador')
        {
          include("menu_admin.phtml");
        }
        elseif (isset($_SESSION["ses_id"]) and isset($_SESSION["privilegio"]) and $_SESSION["privilegio"]=='encargado')
        {
          include("menu_encargado.phtml");
        }
         ?>
      </nav>
      <!-- end of navigation -->

      <div class="contenedor">
      	<br>
      	<br>
        <form name="form" action="" method="post" enctype="multipart/form-data">
	    <?php
	    if(isset($_GET["m"]))
	    {

		    switch($_GET["m"])
		    {
      case '1';
      ?>
            <h3 style="color:red"> La foto no debe exceder los 2 Mb de capacidad.</h3>
          <?php
      break;

      case '2';
      ?>
            <h3 style="color:red"> Solo formato jpeg.</h3>
          <?php
      break;

			case '3';
			?>
	        	<h3 style="color:green"> Activo ingresado correctamente.</h3>
	        <?php
			break;

			case '4';
			?>
	        	<h3 style="color:red"> El codigo de activo ya existe, intente nuevamente. </h3>
	        <?php
			break;
    		}
    	}
    	?>
        <table align="center" width="970">
        <tr>
        <td valign="top" align="center" colspan="2" width="970">
        <h2><strong>Ingresar nuevo activo</strong></h2>
        <br>
        </td>
        </tr>

        <tr>
        <td valign="middle" align="right" width="480">
        Código activo:
        </td>
        <td valign="middle" align="left" width="480">
        <input type="text" name="codigo_activo" maxlength="6" autofocus />
        </td>
        </tr>

        <tr>
        <td valign="middle" align="right" width="480">
        Nombre activo:
        </td>
        <td valign="middle" align="left" width="480">
        <input type="text" name="nombre_activo" />
        </td>
        </tr>

        <tr>
        <td valign="middle" align="right" width="480">
        Categoría activo:
        </td>
        <td valign="middle" align="left" width="480">
            <select name="categoria_activo" id="select">
              <option selected="selected">Elegir categoría</option>
              <?php
                if (empty($categoria))
                {
                  ?>
                  <option value="">No se encontró ninguna categoría.</option>
                  <?php
                }
                else
                {
                  for($i=0;$i<count($categoria);$i++)
                  {
                    ?>
                    <option value="<?php echo $categoria[$i]["id_cat"]; ?>"><?php echo $categoria[$i]["nombre_cat"]; ?></option>
                    <?php
                  }
                }
              ?>
            </select>
        </td>
        </tr>

        <tr>
        <td valign="middle" align="right" width="480">
        Fecha ingreso:
        </td>
        <td valign="middle" align="left" width="480">
        <input type="text" name="fecha_ingreso" class="fecha_ingreso" readonly/>
        </td>
        </tr>


        <tr>
        <td valign="top" align="right" width="480">
        Detalle:
        </td>
        <td valign="middle" align="left" width="480">
        <textarea name="detalle_activo" rows="3" cols="18"></textarea>
        </td>
        </tr>


        <tr>
        <td valign="middle" align="right" width="480">
        Cantidad:
        </td>
        <td valign="middle" align="left" width="480">
        <input type="text" name="cantidad_activo" maxlength="6" onkeypress="return soloNumerosCantidad(event,this.value)"/> U.
        </td>
        </tr>

        <tr>
        <td valign="middle" align="right" width="480">
        Tipo:
        </td>
        <td valign="middle" align="left" width="480">
            <select name="tipo_activo" id="select">
              <option selected="selected">Elegir tipo</option>
              <option value="activo">Activo</option>
              <option value="sub activo">Sub activo</option>
            </select>
        </td>
        </tr>

        <tr>
        <td valign="middle" align="right" width="480">
        Precio:
        </td>
        <td valign="middle" align="left" width="480">
        <input type="text" name="precio_activo" maxlength="6" onkeypress="return soloNumeros(event,this.value)" /> Bs.
        </td>
        </tr>

        <tr>
        <td valign="top" align="right" width="480">
        Ubicación:
        </td>
        <td valign="top" align="left" width="480">
        <input type="file" name="ubicacion_activo" /> (Solo JPG)
        </td>
        </tr>

        <tr>
        <td valign="top" align="right" width="480">
        foto:
        </td>
        <td valign="top" align="left" width="480">
        <input type="file" name="foto_activo" /> (Solo JPG)
        </td>
        </tr>

        <tr>
        <td valign="middle" align="right" width="480">
        Encargado:
        </td>
        <td valign="middle" align="left" width="480">
            <select name="personal_activo" id="select">
              <option selected="selected">Elegir personal</option>
              <?php
                if (empty($personal))
                {
                  ?>
                  <option value="">No se encontró ningun personal.</option>
                  <?php
                }
                else
                {
                  for($i=0;$i<count($personal);$i++)
                  {
                    ?>
                    <option value="<?php echo $personal[$i]["id_usuario"]; ?>"><?php echo $personal[$i]["nombre_usuario"]; ?></option>
                    <?php
                  }
                }
              ?>
            </select>
        </td>
        </tr>

        <tr>
        <td valign="middle" align="right" width="480">
        Vida útil:
        </td>
        <td valign="middle" align="left" width="480">
            <select name="vida_util" id="select">
              <option value="4" selected="selected">4</option>
              <option value="8">8</option>
              <option value="10">10</option>
            </select> Año(s).
        </td>
        </tr>

        <tr>
        <td valign="top" align="center" colspan="2" width="400">
        <br />
        <input type="hidden" name="grabar" value="si" />
        <input name="ingresar" type="button" title="Ingresar activo" onclick="validar_activo();" value="Ingresar activo" />
        </td>
        </tr>

        </table>
        </form>
      </div> <!-- end contenedor -->


      <!-- footer -->
      <div id="footer">
        <p class="copy">&copy; Copyright 2014<span>|</span>Sistema de activos fijos <a href="<?php echo Conectar::ruta();?>" style="color:#FFFFFF">ACTIVES MANAGER</a></p>
        <div class="cl">&nbsp;</div>
      </div>
      <!-- end of footer -->
    </div>
    <!-- end of container -->
  </div>
  <!-- end of shell -->
</div>
<!-- end of wrapper -->
</body>
</html>