<!DOCTYPE html>
<html lang="es-ES">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Actives Manager</title>
  <link rel="shortcut icon" type="image/x-icon" href="<?php echo Conectar::ruta(); ?>images/favicon.ico" />
  <link rel="stylesheet" href="<?php echo Conectar::ruta(); ?>css/style.css" type="text/css" media="all" />
  <link rel="stylesheet" href="<?php echo Conectar::ruta(); ?>css/estilos.css" type="text/css" />
  <link rel="stylesheet" href="<?php echo Conectar::ruta(); ?>css/datePicker.css" type="text/css" />
  <script src="<?php echo Conectar::ruta(); ?>js/jquery-1.8.0.min.js" type="text/javascript"></script>
  <script src="<?php echo Conectar::ruta(); ?>js/date.js" type="text/javascript"></script>
  <script src="<?php echo Conectar::ruta(); ?>js/jquery.datePicker.js" type="text/javascript"></script>
  <!--[if lt IE 9]>
    <script src="js/modernizr.custom.js"></script>
  <![endif]-->
  <script src="<?php echo Conectar::ruta(); ?>js/funciones.js" type="text/javascript"></script>
  <script type="text/javascript">
    jQuery(document).ready(function($) {
        $(function()
        {
            $('.fecha_inicio').datePicker({startDate:'01/01/1996'}).val();
            $('.fecha_fin').datePicker({startDate:'01/01/1996'}).val();
        });
    });
  </script>
</head>
<body>
<!-- wrapper -->
<div id="wrapper">
  <!-- shell -->
  <div class="shell">
    <!-- container -->
    <div class="container">
      <!-- header -->
      <header id="header">
        <h1 id="logo"><a href="#">Active</a></h1>
      </header>
      <!-- end of header -->
      <!-- navigaation -->
      <nav id="navigation">
        <?php include("menu_encargado.phtml"); ?>
      </nav>
      <!-- end of navigation -->

      <div class="contenedor">
      	<br><br><br><br><br>
        <form name="form" action="" method="post" enctype="multipart/form-data">
	    <?php
	    if(isset($_GET["m"]))
	    {

		    switch($_GET["m"])
		    {
          case '1';
          ?>
                <h3 style="color:green"> Mantenimiento asignado correctamente.</h3>
              <?php
          break;
    		}
    	}
    	?>
        <table align="center" width="970">
        <tr>
        <td valign="top" align="center" colspan="2" width="970">
        <h2><strong>Asignar mantenimiento</strong></h2>
        <br>
        <br>
        </td>
        </tr>

        <tr>
        <td valign="middle" align="right" width="480">
        Encargado:
        </td>
        <td valign="middle" align="left" width="480">
            <select name="personal_activo" id="select">
              <option selected="selected">Elegir personal</option>
              <?php
                if (empty($personal))
                {
                  ?>
                  <option value="">No se encontró ningun personal.</option>
                  <?php
                }
                else
                {
                  for($i=0;$i<count($personal);$i++)
                  {
                    ?>
                    <option value="<?php echo $personal[$i]["id_usuario"]; ?>"><?php echo $personal[$i]["nombre_usuario"]; ?></option>
                    <?php
                  }
                }
              ?>
            </select>
        </td>
        </tr>

        <tr>
        <td valign="middle" align="right" width="480">
        Fecha inicio:
        </td>
        <td valign="middle" align="left" width="480">
        <input type="text" name="fecha_inicio" class="fecha_inicio" readonly/>
        </td>
        </tr>

        <tr>
        <td valign="middle" align="right" width="480">
        Fecha fin:
        </td>
        <td valign="middle" align="left" width="480">
        <input type="text" name="fecha_fin" class="fecha_fin" readonly/>
        </td>
        </tr>

        <tr>
        <td valign="middle" align="right" width="480">
        Activo:
        </td>
        <td valign="middle" align="left" width="480">
            <select name="mantenimiento_activo" id="select">
              <option selected="selected">Elegir activo</option>
              <?php
                if (empty($active))
                {
                  ?>
                  <option value="">No se encontró ningun activo.</option>
                  <?php
                }
                else
                {
                  for($i=0;$i<count($active);$i++)
                  {
                    ?>
                    <option value="<?php echo $active[$i]["id_activo"]; ?>"><?php echo $active[$i]["nombre_activo"]; ?></option>
                    <?php
                  }
                }
              ?>
            </select>
        </td>
        </tr>

        <tr>
        <td valign="top" align="center" colspan="2" width="400">
        <br />
        <input type="hidden" name="grabar" value="si" />
        <input name="ingresar" type="button" title="Asignar mantenimiento" onclick="validar_mantenimiento();" value="Asignar mantenimiento" />
        </td>
        </tr>

        </table>
        </form>
      </div> <!-- end contenedor -->


      <!-- footer -->
      <div id="footer">
        <p class="copy">&copy; Copyright 2014<span>|</span>Sistema de activos fijos <a href="<?php echo Conectar::ruta();?>" style="color:#FFFFFF">ACTIVES MANAGER</a></p>
        <div class="cl">&nbsp;</div>
      </div>
      <!-- end of footer -->
    </div>
    <!-- end of container -->
  </div>
  <!-- end of shell -->
</div>
<!-- end of wrapper -->
</body>
</html>