<!DOCTYPE html>
<html lang="es-ES">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Actives Manager</title>
  <link rel="shortcut icon" type="image/x-icon" href="<?php echo Conectar::ruta(); ?>images/favicon.ico" />
  <link rel="stylesheet" href="<?php echo Conectar::ruta(); ?>css/style.css" type="text/css" media="all" />
  <link rel="stylesheet" href="<?php echo Conectar::ruta(); ?>css/estilos.css" type="text/css" />
  <script src="<?php echo Conectar::ruta(); ?>js/jquery-1.8.0.min.js" type="text/javascript"></script>
  <!--[if lt IE 9]>
    <script src="js/modernizr.custom.js"></script>
  <![endif]-->
  <script src="<?php echo Conectar::ruta(); ?>js/funciones.js" type="text/javascript"></script>
  <script src="<?php echo Conectar::ruta(); ?>js/md5.js" type="text/javascript"></script>
</head>
<body>
<!-- wrapper -->
<div id="wrapper">
  <!-- shell -->
  <div class="shell">
    <!-- container -->
    <div class="container">
      <!-- header -->
      <header id="header">
        <h1 id="logo"><a href="<?php echo Conectar::ruta();?>">Active</a></h1>
      </header>
      <!-- end of header -->
      <!-- navigaation -->
      <nav id="navigation">
        <?php include("menu_admin.phtml"); ?>
      </nav>
      <!-- end of navigation -->
      <br>
      <div class="contenedor">
        <br>
        <h2>Cambiar password de administrador</h2>
        <?php
        if(isset($_GET["m"]))
        {
            switch($_GET["m"])
            {
                case '3':
                ?>
                <h3 style="color:green;"> El password fue cambiado con éxito </h3>
                <?php
                break;

                case '4':
                ?>
                <h3 style="color:red;"> Password actual incorrecto </h3>
                <?php
                break;
            }
        }
        ?>
        <form name="form" action="" method="post">
        <table align="center" width="965">
        <tr>
        <td valign="middle" align="center" colspan="2" width="400">
        <br>
        </td>
        </tr>

        <tr>
        <td valign="middle" align="right" width="200">
        <strong>Password Actual:</strong>
        </td>
        <td valign="middle" align="left" width="200">
        <input type="password" name="pass_actual" autofocus/>
        </td>
        </tr>

        <tr>
        <td valign="middle" align="right" width="200">
        <strong>Nuevo Password:</strong>
        </td>
        <td valign="middle" align="left" width="200">
        <input type="password" name="pass"/>
        </td>
        </tr>

        <tr>
        <td valign="middle" align="right" width="200">
        <strong>Repetir Nuevo Password:</strong>
        </td>
        <td valign="middle" align="left" width="200">
        <input type="password" name="pass_1"/>
        </td>
        </tr>

        <tr>
        <td valign="middle" align="center" colspan="2" width="400">
        <br>
        <input type="hidden" name="grabar" value="si" />
        <input type="hidden" name="id_usuario" value="<?php echo $_GET["id_usuario"]?>" />
        <input type="button" value="Cambiar Password" title="Cambiar Password" onclick="cambiar_pass();" />
        </td>
        </tr>
        </table>
        </form>
      </div>
      <!-- footer -->
      <div id="footer">
        <p class="copy">&copy; Copyright 2014<span>|</span>Sistema de activos fijos <a href="<?php echo Conectar::ruta();?>" style="color:#FFFFFF">ACTIVES MANAGER</a></p>
        <div class="cl">&nbsp;</div>
      </div>
      <!-- end of footer -->
    </div>
    <!-- end of container -->
  </div>
  <!-- end of shell -->
</div>
<!-- end of wrapper -->
</body>
</html>