<!DOCTYPE html>
<html lang="es-ES">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Actives Manager</title>
  <link rel="shortcut icon" type="image/x-icon" href="<?php echo Conectar::ruta(); ?>images/favicon.ico" />
  <link rel="stylesheet" href="<?php echo Conectar::ruta(); ?>css/style.css" type="text/css" media="all" />
  <link rel="stylesheet" href="<?php echo Conectar::ruta(); ?>css/estilos.css" type="text/css" />
  <script src="<?php echo Conectar::ruta(); ?>js/jquery-1.8.0.min.js" type="text/javascript"></script>
  <!--[if lt IE 9]>
    <script src="js/modernizr.custom.js"></script>
  <![endif]-->
  <script src="<?php echo Conectar::ruta(); ?>js/funciones.js" type="text/javascript"></script>

</head>
<body>
<!-- wrapper -->
<div id="wrapper">
  <!-- shell -->
  <div class="shell">
    <!-- container -->
    <div class="container">
      <!-- header -->
      <header id="header">
        <h1 id="logo"><a href="<?php echo Conectar::ruta();?>">Active</a></h1>
      </header>
      <!-- end of header -->
      <!-- navigaation -->
      <nav id="navigation">
        <?php include("menu_admin.phtml"); ?>
      </nav>
      <!-- end of navigation -->
      <br>
      <div class="contenedor">
        <h2>Cambiar foto de perfil</h2>
        <form name="form" action="" method="post" enctype="multipart/form-data">
        <?php
        if(isset($_GET["m"]))
        {
            switch($_GET["m"])
            {
                case '1':
                ?>
                <h3 style="color:green;"> Se cambio la foto de perfil con éxito </h3>
                <?php
                break;

                case '2':
                ?>
                <h3 style="color:red;"> La foto no debe exceder los 2 Mb de capacidad. </h3>
                <?php
                break;

                case '3':
                ?>
                <h3 style="color:red;">  Solo formato jpeg. </h3>
                <?php
                break;

                case '4':
                ?>
                <h3 style="color:red;">  Selecciona una foto a subir. </h3>
                <?php
                break;
            }
        }
        ?>
        Foto Actual:
        <br>
            <img src="<?php echo Conectar::ruta()?>pics/<?php echo $perfilgral[0]["foto"];?>" title="Foto de perfil de <?php echo $perfilgral[0]["nombre_usuario"];?>" width="200" height="200" />
        <br />
        <table align="center" width="965">
        <td valign="middle" align="center" colspan="2" width="400">
        </td>

        <tr>
        <td valign="middle" align="right" width="200">
        <strong>Subir foto:</strong> (Solo JPG)
        </td>
        <td valign="middle" align="left" width="200">
    <input type="file" name="foto" />
        </td>
        </tr>

        <tr>
        <td valign="middle" align="center" colspan="2" width="400">
        <br>
        <input type="hidden" name="grabar" value="si" />
        <input type="hidden" name="id_usuario" value="<?php echo $_GET["id_usuario"]?>" />
        <input type="button" value="Subir foto" title="Subir foto" onclick="document.form.submit();" />
        </td>
        </tr>
        </table>
        </form>
      </div>
      <!-- footer -->
      <div id="footer">
        <p class="copy">&copy; Copyright 2014<span>|</span>Sistema de activos fijos <a href="<?php echo Conectar::ruta();?>" style="color:#FFFFFF">ACTIVES MANAGER</a></p>
        <div class="cl">&nbsp;</div>
      </div>
      <!-- end of footer -->
    </div>
    <!-- end of container -->
  </div>
  <!-- end of shell -->
</div>
<!-- end of wrapper -->
</body>
</html>