<!DOCTYPE html>
<html lang="es-ES">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Actives Manager</title>
  <link rel="shortcut icon" type="image/x-icon" href="<?php echo Conectar::ruta(); ?>images/favicon.ico" />
  <link rel="stylesheet" href="<?php echo Conectar::ruta(); ?>css/style.css" type="text/css" media="all" />
  <link rel="stylesheet" href="<?php echo Conectar::ruta(); ?>css/estilos.css" type="text/css" />
  <script src="<?php echo Conectar::ruta(); ?>js/jquery-1.8.0.min.js" type="text/javascript"></script>
  <!--[if lt IE 9]>
    <script src="js/modernizr.custom.js"></script>
  <![endif]-->
  <script src="<?php echo Conectar::ruta(); ?>js/funciones.js" type="text/javascript"></script>

</head>
<body>
<!-- wrapper -->
<div id="wrapper">
  <!-- shell -->
  <div class="shell">
    <!-- container -->
    <div class="container">
      <!-- header -->
      <header id="header">
        <h1 id="logo"><a href="#">Active</a></h1>
      </header>
      <!-- end of header -->
      <!-- navigaation -->
      <nav id="navigation">
        <?php include("menu_admin.phtml"); ?>
      </nav>
      <!-- end of navigation -->

      <div class="contenedor">
      	<br>
      	<br>
        <form name="form" action="" method="post" enctype="multipart/form-data">
	    <?php
	    if(isset($_GET["m"]))
	    {

		    switch($_GET["m"])
		    {
      case '1';
      ?>
            <h3 style="color:red"> La foto no debe exceder los 2 Mb de capacidad.</h3>
          <?php
      break;

      case '2';
      ?>
            <h3 style="color:red"> Solo formato jpeg.</h3>
          <?php
      break;

			case '3';
			?>
	        	<h3 style="color:green"> Usuario editado correctamente.</h3>
	        <?php
			break;

			case '4';
			?>
	        	<h3 style="color:red"> El login de usuario ya existe, intente nuevamente. </h3>
	        <?php
			break;

      case '5';
      ?>
            <h3 style="color:red"> Rellene todos los campos. </h3>
          <?php
      break;

    		}
    	}
    	?>
        <table align="center" width="970">
        <br>
        <tr>
        <td valign="top" align="center" colspan="2" width="400">
        <h2><strong>Editar usuario <?php echo $usu[0]["nombre_usuario"];?></strong></h2>
        <br>
        </td>
        </tr>

        <tr>
        <td valign="middle" align="right" width="200">
        Nombre Completo:
        </td>
        <td valign="middle" align="left" width="200">
        <input type="text" name="nombre" size ="30" value="<?php echo $usu[0]["nombre_usuario"];?>"/>
        </td>
        </tr>

        <tr>
        <td valign="middle" align="right" width="200">
        Login:
        </td>
        <td valign="middle" align="left" width="200">
        <input type="text" name="user" size ="30" value="<?php echo $usu[0]["login"];?>"/>
        </td>
        </tr>

        <tr>
        <td valign="middle" align="right" width="200">
        Tipo:
        </td>
        <td valign="middle" align="left" width="200">
            <select name="tipo" id="select">
              <option value="<?php echo $usu[0]["tipo_usuario"];?>" >
                <?php
                 $tipo_actual = $usu[0]["tipo_usuario"];
                 if ($tipo_actual == "encargado")
                 {
                   echo "Encargado AF";
                 }
                 elseif ($tipo_actual == "personal")
                 {
                   echo "Personal departamento";
                 }
                ?>
              </option>
              <option value="personal">Personal departamento</option>
              <option value="encargado">Encargado AF</option>
            </select>
        </td>
        </tr>

        <tr>
        <td valign="top" align="right" width="200">
        Foto:
        </td>
        <td valign="top" align="left" width="200">
          <input type="file" name="foto" /> (Solo JPG)
          <br />
          foto Actual:
          <a href="<?php echo Conectar::ruta()?>pics/<?php echo $usu[0]["foto"];?>" target="_blank"><img src="<?php echo Conectar::ruta()?>pics/<?php echo $usu[0]["foto"];?>" width="100" height="100" align="middle" title="<?php echo $usu[0]["nombre_usuario"];?>" /></a>
        </td>
        </tr>

        <tr>
        <td valign="top" align="center" colspan="2" width="400">
        <br />
        <input type="hidden" name="grabar" value="si" />
        <input type="hidden" name="id_usuario" value="<?php echo $_GET["id_usuario"]?>" />
        <input type="hidden" name="foto" value="<?php echo $usu[0]["foto"];?>" />
        <input name="ingresar" type="button" title="Editar usuario" onclick="document.form.submit();" value="Editar usuario" />
        </td>
        </tr>
        </table>
        </form>
      </div> <!-- end contenedor -->


      <!-- footer -->
      <div id="footer">
        <p class="copy">&copy; Copyright 2014<span>|</span>Sistema de activos fijos <a href="<?php echo Conectar::ruta();?>" style="color:#FFFFFF">ACTIVES MANAGER</a></p>
        <div class="cl">&nbsp;</div>
      </div>
      <!-- end of footer -->
    </div>
    <!-- end of container -->
  </div>
  <!-- end of shell -->
</div>
<!-- end of wrapper -->
</body>
</html>