<!DOCTYPE html>
<html lang="es-ES">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Actives Manager</title>
  <link rel="shortcut icon" type="image/x-icon" href="<?php echo Conectar::ruta(); ?>images/favicon.ico" />
  <link rel="stylesheet" href="<?php echo Conectar::ruta(); ?>css/style.css" type="text/css" media="all" />
  <link rel="stylesheet" href="<?php echo Conectar::ruta(); ?>css/estilos.css" type="text/css" />
  <script src="<?php echo Conectar::ruta(); ?>js/jquery-1.8.0.min.js" type="text/javascript"></script>
  <!--[if lt IE 9]>
    <script src="js/modernizr.custom.js"></script>
  <![endif]-->
  <script src="<?php echo Conectar::ruta(); ?>js/funciones.js" type="text/javascript"></script>
  <script src="<?php echo Conectar::ruta(); ?>js/md5.js" type="text/javascript"></script>

</head>
<body>
<!-- wrapper -->
<div id="wrapper">
  <!-- shell -->
  <div class="shell">
    <!-- container -->
    <div class="container">
      <!-- header -->
      <header id="header">
        <h1 id="logo"><a href="#">Active</a></h1>
        <div id="sesion"><a href="<?php echo Conectar::ruta(); ?>?accion=logueo">Iniciar Sesión</a></div>
      </header>
      <!-- end of header -->
      <!-- navigaation -->
      <nav id="navigation">
        <?php include("menu_principal.phtml"); ?>
      </nav>
      <!-- end of navigation -->

      <div class="contenedor">
        <form name="form" action="" method="post">
        <?php
        if(isset($_GET["m"]))
        {
            switch($_GET["m"])
            {
                case '1':
                ?>
                <h2 style="color:red;">Los datos están vacíos</h2>
                <?php
                break;

                case '2':
                ?>
                <h2 style="color:red;">Los datos son incorrectos, intente de nuevo porfavor ! </h2>
                <?php
                break;

                case '3':
                ?>
                <h2 style="color:red;"> Debe Loguearse primero para acceder a este contenido. </h2>
                <?php
                break;

                case '4':
                ?>
                <h2 style="color:red;"> Usted esta deshabilitado de ACTIVES MANAGER. </h2>
                <?php
                break;
            }
        }
        ?>
        <br><br>
        <table align="center" width="970">
        <br /><br />
        <tr>
        <td valign="middle" align="center" colspan="2" width="400" style="font-size:24px">
        <strong>Ingrese sus Datos</strong>
        <br /><br />
        </td>
        </tr>

        <tr>
        <td valign="middle" align="right" width="200">
        <b>Login:</b>
        </td>
        <td valign="middle" align="left" width="200">
        <input type="text" name="login" autofocus/>
        </td>
        </tr>

        <tr>
        <td valign="middle" align="right" width="200">
        <b>Password:</b>
        </td>
        <td valign="middle" align="left" width="200">
        <input type="password" name="pass" />
        </td>
        </tr>

        <tr>
        <td valign="middle" align="center" colspan="2" width="400">
          <br>
        <input type="hidden" name="grabar" value="si" />
        <input type="button" value="Entrar" title="Entrar" onclick="validar_logueo();" />
        <br>
        </td>
        </tr>
        </table>
        </form>

      </div><!-- end contenedor -->

      <!-- footer -->
      <div id="footer">
        <p class="copy">&copy; Copyright 2014<span>|</span>Sistema de activos fijos <a href="<?php echo Conectar::ruta();?>" style="color:#FFFFFF">ACTIVES MANAGER</a></p>
        <div class="cl">&nbsp;</div>
      </div>
      <!-- end of footer -->
    </div>
    <!-- end of container -->
  </div>
  <!-- end of shell -->
</div>
<!-- end of wrapper -->
</body>
</html>