<!DOCTYPE html>
<html lang="es-ES">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Actives Manager</title>
  <link rel="shortcut icon" type="image/x-icon" href="<?php echo Conectar::ruta(); ?>images/favicon.ico" />
  <link rel="stylesheet" href="<?php echo Conectar::ruta(); ?>css/style.css" type="text/css" media="all" />
  <link rel="stylesheet" href="<?php echo Conectar::ruta(); ?>css/estilos.css" type="text/css" />
  <script src="<?php echo Conectar::ruta(); ?>js/jquery-1.8.0.min.js" type="text/javascript"></script>
  <!--[if lt IE 9]>
    <script src="js/modernizr.custom.js"></script>
  <![endif]-->
  <script src="<?php echo Conectar::ruta(); ?>js/funciones.js" type="text/javascript"></script>

</head>
<body>
<!-- wrapper -->
<div id="wrapper">
  <!-- shell -->
  <div class="shell">
    <!-- container -->
    <div class="container">
      <!-- header -->
      <header id="header">
        <h1 id="logo"><a href="<?php echo Conectar::ruta();?>">Active</a></h1>
      </header>
      <!-- end of header -->
      <!-- navigaation -->
      <nav id="navigation">
        <?php include("menu_admin.phtml"); ?>
      </nav>
      <!-- end of navigation -->
      <br>
      <div class="contenedor">
        <span style="font-size:18px">
        <table align="center" width="965">
          <br><br>
        <tr>
        <td valign="middle" align="center" colspan="2" width="500">
          <h2>Perfil de administrador</h2>
        <br><br>
        </td>
        </tr>

        <tr>
        <td valign="middle" align="right" width="250">
        <strong>Nombre:</strong>
        </td>
        <td valign="middle" align="left" width="250">
        <?php echo $perfil[0]["nombre_usuario"];?>
        </td>
        </tr>

        <tr>
        <td valign="middle" align="right" width="250">
        <strong>Login:</strong>
        </td>
        <td valign="middle" align="left" width="250">
        <?php echo $perfil[0]["login"];?>
        </td>
        </tr>

        <tr>
        <td valign="middle" align="right" width="250">
        <strong>Estado:</strong>
        </td>
        <td valign="middle" align="left" width="250">
        <?php echo $perfil[0]["estado"];?>
        </td>
        </tr>

        </table>
        </span>
        <br>
        <a href="<?php echo Conectar::ruta();?>?accion=editperfil&id_usuario=<?php echo $perfil[0]["id_usuario"];?>" title="Editar perfil de <?php echo $perfil[0]["nombre_usuario"];?>"><img src="<?php echo Conectar::ruta();?>images/editar.png" border="0" width="48" height="48" /></a>
                     &nbsp &nbsp &nbsp
        <a href="<?php echo Conectar::ruta();?>?accion=cambiarpass_admin&id_usuario=<?php echo $perfil[0]["id_usuario"];?>" title="Cambiar password de <?php echo $perfil[0]["nombre_usuario"];?>"><img src="<?php echo Conectar::ruta();?>images/cambiar_pass.png" border="0" width="48" height="48" /></a>
                     &nbsp &nbsp &nbsp
        <a href="<?php echo Conectar::ruta();?>?accion=cambiarfoto&id_usuario=<?php echo $perfil[0]["id_usuario"];?>" title="Cambiar foto de perfil de <?php echo $perfil[0]["nombre_usuario"];?>"><img src="<?php echo Conectar::ruta();?>images/cambiar_foto.png" border="0" width="48" height="48" /></a>
      </div>
      <!-- footer -->
      <div id="footer">
        <p class="copy">&copy; Copyright 2014<span>|</span>Sistema de activos fijos <a href="<?php echo Conectar::ruta();?>" style="color:#FFFFFF">ACTIVES MANAGER</a></p>
        <div class="cl">&nbsp;</div>
      </div>
      <!-- end of footer -->
    </div>
    <!-- end of container -->
  </div>
  <!-- end of shell -->
</div>
<!-- end of wrapper -->
</body>
</html>