<!DOCTYPE html>
<html lang="es-ES">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Actives Manager</title>
  <link rel="shortcut icon" type="image/x-icon" href="<?php echo Conectar::ruta(); ?>images/favicon.ico" />
  <link rel="stylesheet" href="<?php echo Conectar::ruta(); ?>css/style.css" type="text/css" media="all" />
  <link rel="stylesheet" href="<?php echo Conectar::ruta(); ?>css/estilos.css" type="text/css" />
  <script src="<?php echo Conectar::ruta(); ?>js/jquery-1.8.0.min.js" type="text/javascript"></script>
  <!--[if lt IE 9]>
    <script src="js/modernizr.custom.js"></script>
  <![endif]-->
  <script src="<?php echo Conectar::ruta(); ?>js/funciones.js" type="text/javascript"></script>
  <style type="text/css">
    <!--
    .Estilo1 {font-family:"Arial"; font-size:13px; color: green;}
    .Estilo2 {font-family:"Arial"; font-size:13px; color: red;}
    -->
  </style>
</head>
<body>
<!-- wrapper -->
<div id="wrapper">
  <!-- shell -->
  <div class="shell">
    <!-- container -->
    <div class="container">
      <!-- header -->
      <header id="header">
        <h1 id="logo"><a href="<?php echo Conectar::ruta();?>">Active</a></h1>
      </header>
      <!-- end of header -->
      <!-- navigaation -->
      <nav id="navigation">
        <?php
          if(isset($_SESSION["ses_id"]) and isset($_SESSION["privilegio"]) and $_SESSION["privilegio"]=='administrador')
          {
            include("menu_admin.phtml");
          }
          elseif (isset($_SESSION["ses_id"]) and isset($_SESSION["privilegio"]) and $_SESSION["privilegio"]=='encargado')
          {
            include("menu_encargado.phtml");
          }
          elseif (isset($_SESSION["ses_id"]) and isset($_SESSION["privilegio"]) and $_SESSION["privilegio"]=='personal')
          {
            include("menu_personal.phtml");
          }
          else
          {
            include("menu_principal.phtml");
          }
        ?>
      </nav>
      <!-- end of navigation -->
      <br>
      <div class="contenedor">
        <h3>Registro de asignaciones de mantenimiento</h3>
        <br>
        <?php
        if(isset($_GET["m"]))
        {
          switch($_GET["m"])
          {
            case '1';
            ?>
                  <h3 style="color:green"> La asignación fue eliminada con éxito.</h3>
                <?php
            break;

            case '2';
            ?>
                  <h3 style="color:red"> La asignación no pudo ser eliminada, intente nuevamente.</h3>
                <?php
            break;
          }
        }
        ?>
        <br>
        <div id="contenedor_tabla">
        <div class="barra_deslizante_tabla">
        <?php
        if(empty($record))
        {
        ?>
            <h2 style="color:white;"> Ninguna asignación encontrada </h2>
        <?php
        }
        else
        {
                ?>
                <table align="center" width="965">

                <tr style="background-color:#808080; color:#FFFFFF; font-weight:bold">

                <td valign="middle" align="center" width="55" height="30"  >
                Estado</td>

                <td valign="middle" align="center" width="200" height="30" >
                Nombre activo</td>

                <td valign="middle" align="center" width="150" height="30" >
                Fecha inicio</td>

                <td valign="middle" align="center" width="100" height="30">
                Fecha fin</td>

                <td valign="middle" align="center" width="36">
                Encargado</td>

                <td valign="middle" align="center" width="36">
                Eliminar</td>

                </tr>
                <?php
                for($i=0;$i<count($record);$i++)
                {
                ?>
                    <tr id="<?php echo "tr_$i";?>" style="background-color:#f0f0f0" onMouseMove="tr('<?php echo "tr_$i";?>','#cccccc');" onMouseOut="tr('<?php echo "tr_$i";?>','#f0f0f0');">

                    <td valign="middle" align="center" height="30">
                    <?php
                    $est=$record[$i]['estado_mantenimiento'];
                        if($est == "concluido")
                        {
                            ?>
                            <span class="Estilo1"><strong>
                            <?php
                            echo "Concluido";
                            ?>
                            </strong></span> <?php
                        }
                        elseif($est == "pendiente")
                        {
                            ?>
                            <span class="Estilo2"><strong>
                            <?php
                            echo "Pendiente";
                            ?>
                            </strong></span> <?php
                        }
                    ?>
                    </td>

                    <td valign="middle" align="center">
                    <?php
                    echo $record[$i]["nombre_activo"];
                    ?></td>

                    <td valign="middle" align="center">
                    <?php
                    echo $record[$i]["fecha_inicio"];
                    ?></td>

                    <td valign="middle" align="center">
                    <?php
                    echo $record[$i]["fecha_fin"];
                    ?></td>

                    <td valign="middle" align="center">
                    <?php
                    echo $record[$i]["nombre_usuario"];
                    ?></td>

                    <!--Campo eliminar asignación-->
                    <td valign="middle" align="center" width="50">
                        <a href="#" title="Eliminar asignación de mantenimiento" onclick="eliminar_asign('<?php echo Conectar::ruta();?>?accion=eliminar_asign&id_mantenimiento=<?php echo $record[$i]["id_mantenimiento"];?>')"><img src="<?php echo Conectar::ruta();?>images/eliminar.png" border="0" width="32" height="32" /></a>
                    </td>

                </tr>
                <?php
                }
                ?>
                </table>
        <?php
        }
        ?>
        </div><!--Fin class barra_deslizante_tabla-->
        </div> <!--fin contenedor_tabla-->


      </div>
      <!-- footer -->
      <div id="footer">
        <p class="copy">&copy; Copyright 2014<span>|</span>Sistema de activos fijos <a href="<?php echo Conectar::ruta();?>" style="color:#FFFFFF">ACTIVES MANAGER</a></p>
        <div class="cl">&nbsp;</div>
      </div>
      <!-- end of footer -->
    </div>
    <!-- end of container -->
  </div>
  <!-- end of shell -->
</div>
<!-- end of wrapper -->
</body>
</html>